[workspace]

[package]
name = "snapshot-triggers-tokens"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "26.0.0-rc.1"

[dev-dependencies]
soroban-validation = { path = "../../../shared", features = ["testutils"] }
soroban-sdk = { version = "26.0.0-rc.1", features = ["testutils"] }
