[package]
name = "fuzz-testing"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "alloc"] }
arbitrary = { version = "1.3", features = ["derive"] }
proptest = "1.6"
proptest-arbitrary-interop = "0.1"
