[package]
name = "soroban-validation"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }