[package]
name = "diamond-security"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
facet-adder = { path = "facet-adder" }
facet-multiplier = { path = "facet-multiplier" }
